export const MEMBERS = [
  {
    id: 1,
    name: "Yassine Bouazza",
    plan: "Premium",
    status: "active",
    joined: "2025-01-10",
    expires: "2026-01-10",
    phone: "+213 555 0101",
    avatar: "YB",
  },
  {
    id: 2,
    name: "Amina Khelifi",
    plan: "Basic",
    status: "active",
    joined: "2025-03-01",
    expires: "2026-03-01",
    phone: "+213 555 0202",
    avatar: "AK",
  },
  {
    id: 3,
    name: "Riad Mansouri",
    plan: "Premium",
    status: "expired",
    joined: "2024-03-15",
    expires: "2025-03-15",
    phone: "+213 555 0303",
    avatar: "RM",
  },
  {
    id: 4,
    name: "Nour Benali",
    plan: "Basic",
    status: "new",
    joined: "2026-03-01",
    expires: "2026-04-01",
    phone: "+213 555 0404",
    avatar: "NB",
  },
  {
    id: 5,
    name: "Karim Oukaci",
    plan: "Premium",
    status: "active",
    joined: "2025-06-20",
    expires: "2026-06-20",
    phone: "+213 555 0505",
    avatar: "KO",
  },
  {
    id: 6,
    name: "Sonia Hadjadj",
    plan: "Basic",
    status: "expired",
    joined: "2024-09-01",
    expires: "2025-09-01",
    phone: "+213 555 0606",
    avatar: "SH",
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Whey Protein 1kg",
    category: "Nutrition",
    price: 4500,
    stock: 23,
    sold: 142,
  },
  {
    id: 2,
    name: "Creatine Monohydrate",
    category: "Nutrition",
    price: 2800,
    stock: 15,
    sold: 89,
  },
  {
    id: 3,
    name: "Resistance Bands Set",
    category: "Equipment",
    price: 1200,
    stock: 8,
    sold: 34,
  },
  {
    id: 4,
    name: "Gym Gloves",
    category: "Accessories",
    price: 800,
    stock: 31,
    sold: 67,
  },
  {
    id: 5,
    name: "Shaker Bottle",
    category: "Accessories",
    price: 500,
    stock: 45,
    sold: 210,
  },
  {
    id: 6,
    name: "Pre-Workout 300g",
    category: "Nutrition",
    price: 3200,
    stock: 0,
    sold: 55,
  },
];

export const SUBSCRIPTIONS = [
  {
    id: 1,
    member: "Nour Benali",
    plan: "Basic",
    type: "new",
    date: "2026-03-01",
    amount: 2000,
  },
  {
    id: 2,
    member: "Amina Khelifi",
    plan: "Basic",
    type: "renew",
    date: "2026-03-01",
    amount: 2000,
  },
  {
    id: 3,
    member: "Riad Mansouri",
    plan: "Premium",
    type: "expired",
    date: "2025-03-15",
    amount: 3500,
  },
  {
    id: 4,
    member: "Yassine Bouazza",
    plan: "Premium",
    type: "renew",
    date: "2025-01-10",
    amount: 3500,
  },
  {
    id: 5,
    member: "Sonia Hadjadj",
    plan: "Basic",
    type: "expired",
    date: "2025-09-01",
    amount: 2000,
  },
  {
    id: 6,
    member: "Karim Oukaci",
    plan: "Premium",
    type: "active",
    date: "2025-06-20",
    amount: 3500,
  },
];

export const NAV_ADMIN = [
  { id: "dashboard", label: "Dashboard", icon: "📊" },
  { id: "members", label: "Members", icon: "👥" },
  { id: "subscriptions", label: "Subscriptions", icon: "📋" },
  { id: "products", label: "Products & Sales", icon: "🛍️" },
];
export const NAV_SECRETARY = [
  { id: "members", label: "Members", icon: "👥" },
  { id: "subscriptions", label: "Subscriptions", icon: "📋" },
  { id: "products", label: "Buy Products", icon: "🛍️" },
];
